### ISSUE TITLE
Need more information for the difference between a sampler and ask-and-tell. 

### ISSUE THREAD

**Issue by huynhhuy1401** [CyberAgentAILab/cmaes#108]
# Feature Request

I'm new to Evolution Strategy and I don't understand the difference between a sampler and ask-and-tell interface. Can you give a more detailed explain?

**Comment by c-bata** [comment]
Sampler is a high-level interface intended to perform optimizations from Optuna. ask-and-tell interface is a low-level interface intended to perform optimizations without Optuna.
