### ISSUE TITLE
question about _xnes

### ISSUE THREAD

**Issue by ikalemmon** [CyberAgentAILab/cmaes#155]
# Bug reports

*Please file a bug report here.*

## Expected Behavior

*Please describe the behavior you are expecting*

## Current Behavior and Steps to Reproduce

*What is the current behavior? Please provide detailed steps or example for reproducing.*

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* cmaes version or commit revision:

Sorry, it is not bug, but question about your imprementation.
I couldn't find the appropriate place, so I would like to ask a question here.
In the usage examples of xnes, an example of a minimization was shown. However, the original paper of xnes("Exponential Natural Evolution Strategies") deals with a maximization problem. I checked the code, but I couldn't find any specific changes from the original paper, and I couldn't understand where they switch between the maximization and minimization problems. I would be grateful if you could enlighten me how do you change maximize or minimize.

**Comment by ikalemmon** [comment]
@nomuramasahir0 
I apologize, but would it be possible to answer this question?

**Comment by nomuramasahir0** [comment]
Hi @ikalemmon ,

Thank you for the question. The change of maximization and minimization is absorbed by the utility function (u in the original paper).

* In the original xNES paper, u_i := f(x_i) / n, as it focuses on maximization
* In our implementation, u_i := - f(x_i) / n, as it focuses on minimization

**Comment by ikalemmon** [comment]
@nomuramasahir0 
Thank you for your answer.
But I'm still confused...

I think the implementation of u is here(https://github.com/CyberAgentAILab/cmaes/blob/91bcaca06eef8193d8ee6a65b2a2bec0b5cfb114/cmaes/_xnes.py#L91)

I can't find the change from the paper in that code...
<img width="361" alt="image" src="https://github.com/CyberAgentAILab/cmaes/assets/48440826/7f0d51cb-bd13-494a-9637-e18dcfa3ea95">

**Comment by nomuramasahir0** [comment]
As for the fitness shaping, for example, please see [the NES tutorial slide](https://github.com/nomuramasahir0/cec2023-tutorial/blob/main/nes-tutorial-cec2023.pdf), pp.23.

**Comment by ikalemmon** [comment]
@nomuramasahir0 
thanks, I checked it!
Could you show me the relevant part of the code in _xnes.py?

**Comment by ikalemmon** [comment]
Sorry, I understand!!
Thank you for your detailed expranation!!

**Comment by nomuramasahir0** [comment]
Sure!
