### ISSUE TITLE
documentation issue: what is the best value for popsize?

### ISSUE THREAD

**Issue by FlorinAndrei** [CyberAgentAILab/cmaes#161]
# Bug reports

With Optuna, if I use `CmaEsSampler()` with `restart_strategy='ipop'` then the recommended `inc_popsize` (according to the documentation) is 2.

But what if I use `restart_strategy='bipop'`? Is `inc_popsize=2` still optimal? And what is the optimal `popsize` in that case?

## Expected Behavior

The documentation should provide some hints, the way it does for `inc_popsize`.

## Current Behavior and Steps to Reproduce

The documentation does not provide hints.

**Comment by nomuramasahir0** [comment]
The optimal setting is contingent upon the specific problem at hand. It is important to recognize that a setting of inc_popsize=2 in IPOP-CMA might not be universally optimal, as its effectiveness can vary depending on the structure of the problem. In our implementation, we have adhered to the guidelines presented in the original paper. However, we have not conducted an extensive investigation into the impact of varying these settings.
