### ISSUE TITLE
How to set multi-dimensional Sigma

### ISSUE THREAD

**Issue by shenao1994** [CyberAgentAILab/cmaes#176]
Hello. I optimize the six degree of freedom task. Therefore, my goal is to set a **Sigma** for each channel. What should I do? I input a **Sigma** list, like this:
`sigma = [1 , 15, 30, 25, 25, 50]`
Thank you!

**Comment by nomuramasahir0** [comment]
Hi @shenao1994 ,

Recently, @aschepelmann provided an excellent example for achieving that.
https://github.com/CyberAgentAILab/cmaes/issues/173#issuecomment-2034710431
I believe this example will be helpful for you.

**Comment by shenao1994** [comment]
> Hi @shenao1994 ,
> 
> Recently, @aschepelmann provided an excellent example for achieving that. [#173 (comment)](https://github.com/CyberAgentAILab/cmaes/issues/173#issuecomment-2034710431) I believe this example will be helpful for you.

Thank you very much for your help! It's worked.
