### ISSUE TITLE
Update raw.githubusercontent.com

### ISSUE THREAD

**Issue by nomuramasahir0** [CyberAgentAILab/cmaes#180]
I observed the figure of CMA with Margin was not working before the authentication of CyberAgent organization.
Anyway one easy idea to fix is to include the figure itself, rather than link.

**Comment by c-bata** [comment]
<img width="1383" alt="Screenshot 2024-05-30 12 00 39" src="https://github.com/CyberAgentAILab/cmaes/assets/5564044/bd6d796f-1593-4c4f-821b-0fa2b757253f">

I can see the figure on the Google Chrome's secret window :eyes:

**Comment by nomuramasahir0** [comment]
Yes, now I also can see it, but before the authentication(?) of CA (conducted at the time of this issue created), I was not able to see the figure. I confirmed this behavior in a different browser.
I'm not sure why it was happened, but anyway I think hosting the figure in this repository is safe.
I have received consent from @ha-mano (owner of https://github.com/EvoConJP/CMA-ES_with_Margin), so the figure will be added to this repository.

**Comment by c-bata** [comment]
Adding the figure in this repository make `pip install git+https://github.com/CyberAgentAILab/cmaes.git` slower. So I recommend a workaround where you upload the file to the issue and use the link to the uploaded image, as shown below:

https://github.com/CyberAgentAILab/cmaes/issues/1

**Comment by nomuramasahir0** [comment]
Oh, you're right! Thank you for the advice.

@ha-mano Please follow the above comment by @c-bata .

**Comment by ha-mano** [comment]
Thank you for your guidance and support in resolving this issue!
The issue has been addressed as discussed. Please refer to pull request #181 for more details.

**Comment by nomuramasahir0** [comment]
Thanks! It looks great.
